# =============================================
# SNORT CONFIGURATION — Web Server
# Snort 2.9.20 (compiled from source)
# =============================================

# Network variables
ipvar HOME_NET 172.20.0.0/24,172.21.0.0/24
ipvar EXTERNAL_NET !$HOME_NET
ipvar HTTP_SERVERS 172.20.0.10
ipvar SQL_SERVERS 172.21.0.20

portvar HTTP_PORTS [80,443]
portvar MYSQL_PORTS 3306

# Paths
var RULE_PATH /etc/snort/rules
var LOG_PATH /var/log/snort

# =============================================
# INCLUDE RULES (3 jenis)
# =============================================

# 1. Rules buatan sendiri (lokal)
include $RULE_PATH/local.rules

# 2. Rules komunitas (download dari snort.org)
include $RULE_PATH/community.rules

# 3. Rules ICMP (manual update)
include $RULE_PATH/icmp.rules