# =============================================
# SNORT CONFIGURATION — Web Server
# Snort 2.9.20 (Debian Buster apt package)
# =============================================

# Network variables
ipvar HOME_NET [172.20.0.0/24,172.21.0.0/24]
ipvar EXTERNAL_NET !$HOME_NET
ipvar HTTP_SERVERS 172.20.0.10
ipvar SQL_SERVERS 172.21.0.20

portvar HTTP_PORTS [80,443]
portvar MYSQL_PORTS 3306

# Paths
var RULE_PATH /etc/snort/rules
var LOG_PATH /var/log/snort

# DAQ config
config daq: pcap
config daq_mode: passive

# Logging
config logdir: /var/log/snort

# Other
config utc
config show_year
config checksum_mode: none

# Output
output alert_fast: alert.log
output log_tcpdump: packets.log

# =============================================
# CLASSIFICATIONS (wajib untuk classtype di rules)
# =============================================
config classification: web-application-attack,Web Application Attack,1
config classification: attempted-user,Attempted User Privilege Gain,1
config classification: attempted-dos,Attempted Denial of Service,2
config classification: attempted-recon,Attempted Information Leak,2
config classification: misc-activity,Misc activity,3

# =============================================
# INCLUDE RULES (3 jenis)
# =============================================

# 1. Rules buatan sendiri (lokal)
include $RULE_PATH/local.rules

# 2. Rules komunitas (download dari snort.org)
include $RULE_PATH/community.rules

# 3. Rules ICMP (manual update)
include $RULE_PATH/icmp.rules