# =============================================
# SNORT CONFIGURATION — DB Server
# =============================================

# Network variables
ipvar HOME_NET 172.21.0.0/24
ipvar EXTERNAL_NET !$HOME_NET
ipvar SQL_SERVERS 172.21.0.20
ipvar HTTP_SERVERS 172.20.0.10

portvar MYSQL_PORTS 3306

# Paths
var RULE_PATH /etc/snort/rules
var LOG_PATH /var/log/snort

# Output — simpan alert ke file
output alert_fast: /var/log/snort/alert.log
output log_tcpdump: /var/log/snort/packets.log

# Preprocessors
preprocessor frag3_global: max_frags 65536
preprocessor frag3_engine: policy first detect_anomalies

preprocessor stream5_global: track_tcp yes, track_udp yes, \
    track_icmp yes, max_tcp 262144
preprocessor stream5_tcp: policy first, detect_anomalies, \
    require_3whs 180

# =============================================
# INCLUDE RULES
# =============================================

# 1. Rules buatan sendiri (lokal) — fokus proteksi DB
include $RULE_PATH/local.rules

# 2. Rules ICMP (manual update)
include $RULE_PATH/icmp.rules
